<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Scriban" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Gw2Unlocks.Common\Gw2Unlocks.Common.csproj" />
    <ProjectReference Include="..\..\UnlockClassifier\Gw2Unlocks.UnlockClassifier.Cache\Gw2Unlocks.UnlockClassifier.Cache.csproj" />
    <ProjectReference Include="..\..\UnlockClassifier\Gw2Unlocks.UnlockClassifier\Gw2Unlocks.UnlockClassifier.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="page.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
